- name: Copy prometheus configuration
  template: src=config/prometheus.yml dest={{ prometheus_directory }}/prometheus.yml
  when: prometheus_custom_config is not defined

- name: Copy prometheus configuration
  template: src={{ prometheus_custom_config }} dest={{ prometheus_directory }}/prometheus.yml
  when: prometheus_custom_config is defined


