global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'prometheus'

    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'collectd'

    scrape_interval: 10s

    target_groups:
      - targets: ['localhost:9103']
        labels: 
          group: monitor
